server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true #是否注册ip到eureka
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator
    service-url:
      defaultZone: http://${hush-boot.eureka.name}:${hush-boot.eureka.password}@localhost:8761/eureka/

management: #管理配置
  context-path: /hush-management

endpoints:
  bus:
    enabled: true #开启bus总线操作
  shutdown:
    enabled: true #开启shutdown操作

security: #basic认证, 用户名/密码
  user:
    name: lawrence
    password: lawrence-config

hush-boot: #注册到eureka的basic认证, 用户名/密码
  eureka:
    name: lawrence
    password: lawrence-registry

spring:
  profiles:
    active: native #使用本地配置



---
#本地配置profile
spring:
  profiles: native
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: lawrence
    password: lawrence
  cloud:
    config:
      server:
        native:
          search-locations: config-repo/native



---
#远程git配置profile
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          basedir: config-repo
          uri: https://gitee.com/lawrencetao/hush-config
          search-paths: /test
          username: taobao3809@163.com
          password: GiteeTao3809
          force-pull: true
