eureka:
  instance:
    prefer-ip-address: true #是否注册ip到eureka
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          basedir: config-repo
          uri: https://gitee.com/lawrencetao/hush-config
          search-paths: /test
          username: taobao3809@163.com
          password: GiteeTao3809
          force-pull: true
