eureka:
  instance:
    prefer-ip-address: true #是否注册ip到eureka
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true #开启hystrix支持, 降级处理配置
  compression:
    request:
      enabled: true #开启请求gzip压缩
    response:
      enabled: true #开启响应gzip压缩
  client:
    config:
      default:
        loggerLevel: headers #默认feign日志级别

logging:
  level:
    com:
      lawrence:
        hush:
          restapi:
            ServiceClient: debug #ServiceClient客户端接口的日志级别