server:
  port: 8771

eureka:
  instance:
    prefer-ip-address: true #是否注册ip到eureka
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator
    service-url:
      defaultZone: http://${hush-boot.eureka.name}:${hush-boot.eureka.password}@localhost:8761/eureka/

management: #管理配置
  context-path: /hush-management

hush-boot: #注册到eureka的basic认证, 用户名/密码
  eureka:
    name: lawrence
    password: lawrence-registry

turbine:
  aggregator:
    cluster-config: HUSH-WEBAPP #监控链接turbine.stream中的cluster参数
  instanceUrlSuffix: /hush-management/hystrix.stream #匹配客户端的context-path
  app-config: hush-webapp
  combine-host-port: true #以端口号区分客户端
