management: #管理配置
  context-path: /hush-management

security: #basic认证, 用户名/密码
  user:
    name: lawrence
    password: lawrence-registry
spring:
  profiles:
    active: single



---
spring:
  profiles: single

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #是否以ip注册eureka
  client:
    register-with-eureka: false #是否注册自身到eureka
    fetch-registry: false #是否开启检索同步
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/



---
spring:
  profiles: cluster8761

server:
  port: 8761
  next-port: 8762

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #是否以ip注册eureka
  client:
    register-with-eureka: true #是否注册自身到eureka
    fetch-registry: true #是否开启检索同步
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.next-port}/eureka/



---
spring:
  profiles: cluster8762

server:
  port: 8762
  next-port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #是否以ip注册eureka
  client:
    register-with-eureka: true #是否注册自身到eureka
    fetch-registry: true #是否开启检索同步
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.next-port}/eureka/
