eureka:
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator

management:
  context-path: /hush-management

spring:
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: lawrence
    password: lawrence
  redis:
    host: 127.0.0.1
    port: 6379
    password: lawrence

hush-admin:
  dynamic:
    param: lawrence
