eureka:
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator

management: #管理配置
  context-path: /hush-management

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  aop:
    proxy-target-class: true #代理模式Cglib
  zipkin:
    base-url: hush-zipkin
  sleuth:
    sampler:
      percentage: 1.0 #日志收集百分比
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: lawrence
    password: lawrence
  redis:
    host: localhost
    port: 6379
    password: lawrence

hush-admin:
  switch: #功能开关
    swagger2-open: true #是否开启swagger2
    multi-datasource-open: true #是否开启多数据源
  dynamic: #动态参数, 通过config总线刷新
    param: lawrence
  datasource:
    default: #默认数据源
      url: jdbc:mysql://172.168.0.21:3306/hush?Unicode=true&characterEncoding=utf8&useSSL=false
      username: lima_user
      password: Mysql@1234
    extra: #其他数据源
      url: jdbc:mysql://172.168.0.21:3306/hush_mirror?Unicode=true&characterEncoding=utf8&useSSL=false
      username: lima_user
      password: Mysql@1234

mybatis:
  mapper-locations: classpath:com/lawrence/hush/mapper/*.xml
  type-aliases-package: com.lawrence.hush.model,com.lawrence.hush.view
  config-location: classpath:mybatis-config.xml

pagehelper:
  helper-dialect: mysql
  row-bounds-with-count: true
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
