eureka:
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator

management:
  context-path: /hush-management

spring:
  zipkin:
    base-url: http://hush-zipkin
  sleuth:
    sampler:
      percentage: 1.0 #日志收集百分比
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: lawrence
    password: lawrence
  redis:
    host: localhost
    port: 6379
    password: lawrence

hush-admin:
  dynamic:
    param: lawrence
