server:
  port: 8781

eureka:
  instance:
    prefer-ip-address: true #是否注册ip到eureka
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator
    service-url:
      defaultZone: http://${hush-boot.eureka.name}:${hush-boot.eureka.password}@localhost:8761/eureka/

management:
  context-path: /hush-management

security:
  user:
    name: lawrence
    password: lawrence-monitor

hush-boot:
  eureka:
    name: lawrence
    password: lawrence-registry

turbine:
  stream:
    port: 8989

spring:
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: lawrence
    password: lawrence
