server:
  port: 8781

eureka:
  instance:
    prefer-ip-address: true #是否注册ip到eureka
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator
    service-url:
      defaultZone: http://${hush-boot.eureka.name}:${hush-boot.eureka.password}@localhost:8761/eureka/

management: #管理配置
  context-path: /hush-management

security: #basic认证, 用户名/密码
  user:
    name: lawrence
    password: lawrence-monitor

hush-boot: #注册到eureka的basic认证, 用户名/密码
  eureka:
    name: lawrence
    password: lawrence-registry

turbine:
  stream:
    port: 8989 #turbine-stream聚合端口

spring:
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: lawrence
    password: lawrence
