server:
  port: 9411

eureka:
  instance:
    prefer-ip-address: true #是否注册ip到eureka
  client:
    healthcheck:
      enabled: true #eureka将健康检查交给actuator
    service-url:
      defaultZone: http://${hush-boot.eureka.name}:${hush-boot.eureka.password}@localhost:8761/eureka/

management: #管理配置
  context-path: /hush-management

security: #basic认证, 用户名/密码
  user:
    name: lawrence
    password: lawrence-zipkin

hush-boot: #注册到eureka的basic认证, 用户名/密码
  eureka:
    name: lawrence
    password: lawrence-registry

zipkin:
  storage:
    type: mysql #zipkin链路追踪信息存储到mysql

spring:
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: lawrence
    password: lawrence
  datasource:
    schema: classpath:mysql.sql #zipkin调用mysql脚本
    url: jdbc:mysql://172.168.0.21:3306/hush?Unicode=true&characterEncoding=utf8&useSSL=false
    username: lima_user
    password: Mysql@1234
    continue-on-error: true

